eureka:
  client:
    serviceUrl:
      defaultZone: http://https://spring-cloud-eurekaserver.onrender.com:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      prefer-ip-address: false
server:
  port: 8888
spring:
  application:
    name: load-balancer
